/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables.records;

import brs.schema.tables.Properties;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertiesRecord extends UpdatableRecordImpl<PropertiesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB.properties.db_key</code>.
     */
    public void setDbKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.properties.db_key</code>.
     */
    public String getDbKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB.properties.db_value</code>.
     */
    public void setDbValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.properties.db_value</code>.
     */
    public String getDbValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Properties.PROPERTIES.DB_KEY;
    }

    @Override
    public Field<String> field2() {
        return Properties.PROPERTIES.DB_VALUE;
    }

    @Override
    public String component1() {
        return getDbKey();
    }

    @Override
    public String component2() {
        return getDbValue();
    }

    @Override
    public String value1() {
        return getDbKey();
    }

    @Override
    public String value2() {
        return getDbValue();
    }

    @Override
    public PropertiesRecord value1(String value) {
        setDbKey(value);
        return this;
    }

    @Override
    public PropertiesRecord value2(String value) {
        setDbValue(value);
        return this;
    }

    @Override
    public PropertiesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertiesRecord
     */
    public PropertiesRecord() {
        super(Properties.PROPERTIES);
    }

    /**
     * Create a detached, initialised PropertiesRecord
     */
    public PropertiesRecord(String dbKey, String dbValue) {
        super(Properties.PROPERTIES);

        setDbKey(dbKey);
        setDbValue(dbValue);
    }
}