/*
 * This file is generated by jOOQ.
 */
package application.module.node.schema;

import application.module.node.schema.tables.Account;
import application.module.node.schema.tables.AccountAsset;
import application.module.node.schema.tables.AccountBalance;
import application.module.node.schema.tables.Alias;
import application.module.node.schema.tables.AliasOffer;
import application.module.node.schema.tables.AskOrder;
import application.module.node.schema.tables.Asset;
import application.module.node.schema.tables.AssetTransfer;
import application.module.node.schema.tables.At;
import application.module.node.schema.tables.AtMap;
import application.module.node.schema.tables.AtState;
import application.module.node.schema.tables.BidOrder;
import application.module.node.schema.tables.Block;
import application.module.node.schema.tables.Escrow;
import application.module.node.schema.tables.EscrowDecision;
import application.module.node.schema.tables.FlywaySchemaHistory;
import application.module.node.schema.tables.Goods;
import application.module.node.schema.tables.IndirectIncoming;
import application.module.node.schema.tables.Peer;
import application.module.node.schema.tables.Properties;
import application.module.node.schema.tables.Purchase;
import application.module.node.schema.tables.PurchaseFeedback;
import application.module.node.schema.tables.PurchasePublicFeedback;
import application.module.node.schema.tables.RewardRecipAssign;
import application.module.node.schema.tables.Subscription;
import application.module.node.schema.tables.Trade;
import application.module.node.schema.tables.Transaction;
import application.module.node.schema.tables.UnconfirmedTransaction;

/**
 * Convenience access to all tables in DB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>DB.account_asset</code>.
     */
    public static final AccountAsset ACCOUNT_ASSET = AccountAsset.ACCOUNT_ASSET;

    /**
     * The table <code>DB.account_balance</code>.
     */
    public static final AccountBalance ACCOUNT_BALANCE = AccountBalance.ACCOUNT_BALANCE;

    /**
     * The table <code>DB.alias</code>.
     */
    public static final Alias ALIAS = Alias.ALIAS;

    /**
     * The table <code>DB.alias_offer</code>.
     */
    public static final AliasOffer ALIAS_OFFER = AliasOffer.ALIAS_OFFER;

    /**
     * The table <code>DB.ask_order</code>.
     */
    public static final AskOrder ASK_ORDER = AskOrder.ASK_ORDER;

    /**
     * The table <code>DB.asset</code>.
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>DB.asset_transfer</code>.
     */
    public static final AssetTransfer ASSET_TRANSFER = AssetTransfer.ASSET_TRANSFER;

    /**
     * The table <code>DB.at</code>.
     */
    public static final At AT = At.AT;

    /**
     * The table <code>DB.at_map</code>.
     */
    public static final AtMap AT_MAP = AtMap.AT_MAP;

    /**
     * The table <code>DB.at_state</code>.
     */
    public static final AtState AT_STATE = AtState.AT_STATE;

    /**
     * The table <code>DB.bid_order</code>.
     */
    public static final BidOrder BID_ORDER = BidOrder.BID_ORDER;

    /**
     * The table <code>DB.block</code>.
     */
    public static final Block BLOCK = Block.BLOCK;

    /**
     * The table <code>DB.escrow</code>.
     */
    public static final Escrow ESCROW = Escrow.ESCROW;

    /**
     * The table <code>DB.escrow_decision</code>.
     */
    public static final EscrowDecision ESCROW_DECISION = EscrowDecision.ESCROW_DECISION;

    /**
     * The table <code>DB.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>DB.goods</code>.
     */
    public static final Goods GOODS = Goods.GOODS;

    /**
     * The table <code>DB.indirect_incoming</code>.
     */
    public static final IndirectIncoming INDIRECT_INCOMING = IndirectIncoming.INDIRECT_INCOMING;

    /**
     * The table <code>DB.peer</code>.
     */
    public static final Peer PEER = Peer.PEER;

    /**
     * The table <code>DB.properties</code>.
     */
    public static final Properties PROPERTIES = Properties.PROPERTIES;

    /**
     * The table <code>DB.purchase</code>.
     */
    public static final Purchase PURCHASE = Purchase.PURCHASE;

    /**
     * The table <code>DB.purchase_feedback</code>.
     */
    public static final PurchaseFeedback PURCHASE_FEEDBACK = PurchaseFeedback.PURCHASE_FEEDBACK;

    /**
     * The table <code>DB.purchase_public_feedback</code>.
     */
    public static final PurchasePublicFeedback PURCHASE_PUBLIC_FEEDBACK = PurchasePublicFeedback.PURCHASE_PUBLIC_FEEDBACK;

    /**
     * The table <code>DB.reward_recip_assign</code>.
     */
    public static final RewardRecipAssign REWARD_RECIP_ASSIGN = RewardRecipAssign.REWARD_RECIP_ASSIGN;

    /**
     * The table <code>DB.subscription</code>.
     */
    public static final Subscription SUBSCRIPTION = Subscription.SUBSCRIPTION;

    /**
     * The table <code>DB.trade</code>.
     */
    public static final Trade TRADE = Trade.TRADE;

    /**
     * The table <code>DB.transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>DB.unconfirmed_transaction</code>.
     */
    public static final UnconfirmedTransaction UNCONFIRMED_TRANSACTION = UnconfirmedTransaction.UNCONFIRMED_TRANSACTION;
}
