# Node Module - Default Logging Configuration
# Location: resources/conf/node/logging/
# Loaded from: classpath:/conf/node/logging/

.level.application.module.node=INFO
.level.application.module.node.services=INFO
.level.application.module.node.db=INFO
.level.application.module.node.web=INFO
.level.application.module.node.blockchain=INFO
.level.application.module.node.peer=INFO
.level.application.module.node.gui=INFO
.level.node=INFO
.level.node.db.store.DerivedTableManager=OFF