package application.module.node.gui.wizard.steps;

import application.module.node.gui.wizard.WizardContext;
import application.module.node.gui.wizard.WizardStep;
import application.module.node.profile.NodeProfileRepository;
import application.module.node.profile.ProfileNameSuggester;
import application.utils.gui.GuiFontManager;

import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import java.util.Set;
import java.util.function.Supplier;

/**
 * Wizard step 2 — node name, network and ports.
 * <p>
 * The suggested name is generated by the SSOT ({@link ProfileNameSuggester}) from the
 * selected context (network + engine + port), with a {@code _01/_02/...} suffix when the
 * base name is taken. The "taken names" source is injectable so unit tests can run
 * against a sandbox without touching the real {@code conf/} tree.
 * </p>
 */
public class NodeConfigurationStep implements WizardStep {

    private final JPanel panel = new JPanel();
    private final JRadioButton suggestedRadio = new JRadioButton("Use suggested name", true);
    private final JRadioButton customRadio = new JRadioButton("Custom name");
    private final JTextField nameField = new JTextField(28);
    private final JCheckBox testnetBox = new JCheckBox("Testnet (default: mainnet)");
    private final JCheckBox useDefaultsBox = new JCheckBox("Use default ports (recommended)", true);
    private final JTextField apiPortField = new JTextField("8125", 8);
    private final JTextField p2pPortField = new JTextField("8123", 8);
    private final JTextField wsPortField = new JTextField("8126", 8);
    private final Supplier<Set<String>> takenNames;

    public NodeConfigurationStep() {
        this(() -> new java.util.HashSet<>(NodeProfileRepository.discoverProfileNames()));
    }

    /** @param takenNames source of existing profile names (SSOT: repository discovery; injectable for tests). */
    public NodeConfigurationStep(java.util.function.Supplier<java.util.Set<String>> takenNames) {
        this.takenNames = takenNames;
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setOpaque(false);

        JLabel title = new JLabel("2. Configure the node profile");
        title.setFont(title.getFont().deriveFont(java.awt.Font.BOLD, 14f));
        GuiFontManager.applyDefaultFont(title);
        panel.add(title);

        suggestedRadio.addActionListener(e -> {
            suggestedRadio.setSelected(true);
            customRadio.setSelected(false);
            nameField.setEnabled(false);
        });
        customRadio.addActionListener(e -> {
            customRadio.setSelected(true);
            suggestedRadio.setSelected(false);
            nameField.setEnabled(true);
        });
        nameField.setEnabled(false);
        panel.add(suggestedRadio);
        panel.add(customRadio);
        panel.add(nameField);
        panel.add(testnetBox);

        JPanel portsPanel = new JPanel();
        portsPanel.setLayout(new BoxLayout(portsPanel, BoxLayout.Y_AXIS));
        portsPanel.setOpaque(false);
        useDefaultsBox.addActionListener(e -> {
            boolean custom = !useDefaultsBox.isSelected();
            apiPortField.setEnabled(custom);
            p2pPortField.setEnabled(custom);
            wsPortField.setEnabled(custom);
        });
        apiPortField.setEnabled(false);
        p2pPortField.setEnabled(false);
        wsPortField.setEnabled(false);
        portsPanel.add(useDefaultsBox);
        portsPanel.add(portRow("API port:", apiPortField));
        portsPanel.add(portRow("P2P port:", p2pPortField));
        portsPanel.add(portRow("WS port:", wsPortField));
        panel.add(portsPanel);
    }

    private JPanel portRow(String label, JTextField field) {
        JPanel row = new JPanel();
        row.setLayout(new BoxLayout(row, BoxLayout.X_AXIS));
        row.setOpaque(false);
        JLabel l = new JLabel(label);
        l.setPreferredSize(new java.awt.Dimension(90, 24));
        GuiFontManager.applyDefaultFont(l);
        GuiFontManager.applyDefaultFont(field);
        row.add(l);
        row.add(field);
        return row;
    }

    // ── Accessors (also used by tests) ───────────────────────────────────

    public boolean isCustomName() {
        return customRadio.isSelected();
    }

    public String getCustomName() {
        return nameField.getText().trim();
    }

    public boolean isTestnet() {
        return testnetBox.isSelected();
    }

    public boolean isUseDefaultPorts() {
        return useDefaultsBox.isSelected();
    }

    public String getApiPortText() {
        return apiPortField.getText().trim();
    }

    public String getP2pPortText() {
        return p2pPortField.getText().trim();
    }

    public String getWsPortText() {
        return wsPortField.getText().trim();
    }

    private int parsePort(String what, String text) {
        try {
            int p = Integer.parseInt(text);
            if (p < 1 || p > 65535) {
                throw new NumberFormatException();
            }
            return p;
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid " + what + ": " + text);
        }
    }

    /**
     * Resolves the profile name for the current UI state + context (suggested or custom).
     * Deterministic: the suggestion is name/context-based (not creation-order-based).
     */
    public String resolveName(WizardContext context) {
        if (customRadio.isSelected()) {
            return nameField.getText().trim();
        }
        boolean nonDefaultPorts = !useDefaultsBox.isSelected();
        int apiPort = nonDefaultPorts ? parsePort("API port", getApiPortText()) : 0;
        String engineKey = context.getEngine() == null ? "sqlite" : context.getEngine().getSettingsKey();
        String base = ProfileNameSuggester.baseName(testnetBox.isSelected(), engineKey, nonDefaultPorts, apiPort);
        return ProfileNameSuggester.nextAvailableName(base, takenNames.get());
    }

    @Override
    public String getId() {
        return "node-configuration";
    }

    @Override
    public String getTitle() {
        return "Node configuration";
    }

    @Override
    public JComponent getPanel() {
        return panel;
    }

    @Override
    public String validate(WizardContext context) {
        String name = resolveName(context);
        if (name.isEmpty()) {
            return "Profile name is required.";
        }
        if (!name.matches("[A-Za-z0-9._-]+")) {
            return "Invalid profile name '" + name + "' (allowed: letters, digits, '.', '_', '-').";
        }
        if (NodeProfileRepository.isReservedProfileName(name)) {
            return "Profile name '" + name + "' is reserved.";
        }
        if (takenNames.get().contains(name)) {
            return "A profile named '" + name + "' already exists.";
        }
        if (!useDefaultsBox.isSelected()) {
            try {
                parsePort("API port", getApiPortText());
                parsePort("P2P port", getP2pPortText());
                parsePort("WS port", getWsPortText());
            } catch (IllegalArgumentException e) {
                return e.getMessage();
            }
        }
        return null;
    }

    @Override
    public void onExit(WizardContext context) {
        context.setName(resolveName(context));
        context.setTestnet(testnetBox.isSelected());
        context.setUseDefaultPorts(useDefaultsBox.isSelected());
        if (!useDefaultsBox.isSelected()) {
            context.setApiPort(parsePort("API port", getApiPortText()));
            context.setP2pPort(parsePort("P2P port", getP2pPortText()));
            context.setWsPort(parsePort("WS port", getWsPortText()));
        }
    }
}