/*
 * This file is generated by jOOQ.
 */
package application.module.node.schema.tables;

import application.module.node.schema.Db;
import application.module.node.schema.Keys;
import application.module.node.schema.tables.records.PropertiesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Properties extends TableImpl<PropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.properties</code>
     */
    public static final Properties PROPERTIES = new Properties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PropertiesRecord> getRecordType() {
        return PropertiesRecord.class;
    }

    /**
     * The column <code>DB.properties.db_key</code>.
     */
    public final TableField<PropertiesRecord, String> DB_KEY = createField(DSL.name("db_key"),
            SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>DB.properties.db_value</code>.
     */
    public final TableField<PropertiesRecord, String> DB_VALUE = createField(DSL.name("db_value"), SQLDataType.CLOB,
            this, "");

    private Properties(Name alias, Table<PropertiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Properties(Name alias, Table<PropertiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.properties</code> table reference
     */
    public Properties(String alias) {
        this(DSL.name(alias), PROPERTIES);
    }

    /**
     * Create an aliased <code>DB.properties</code> table reference
     */
    public Properties(Name alias) {
        this(alias, PROPERTIES);
    }

    /**
     * Create a <code>DB.properties</code> table reference
     */
    public Properties() {
        this(DSL.name("properties"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public UniqueKey<PropertiesRecord> getPrimaryKey() {
        return Keys.KEY_PROPERTIES_PRIMARY;
    }

    @Override
    public Properties as(String alias) {
        return new Properties(DSL.name(alias), this);
    }

    @Override
    public Properties as(Name alias) {
        return new Properties(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Properties rename(String name) {
        return new Properties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Properties rename(Name name) {
        return new Properties(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}