name: Draft release for Signum Node

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.8.0)'
        required: true

jobs:
  build-node:
    name: Build and Package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        shell: cmd
        run: |
          echo VERSION=${{release_tag}}
          echo VERSION=${{release_tag}} >> %GITHUB_ENV%

      - name: Update Wallets
        shell: bash
        run: |
          cd ./ci
          ./updatePhoenix.sh
          ./updateClassic.sh

      - name: Set up Java 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build artifacts
        run: ./gradlew unzipWindowsJDK shadowJar jpackageWin zipWinExe release

      - name: Create GitHub Release Draft
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Signum Node ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload - signum-node.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node.zip
          asset_name: signum-node-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload - signum-node-win_x64.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node-win_x64.zip
          asset_name: signum-node-${{ env.VERSION }}-win_x64.zip
          asset_content_type: application/zip
