name: Draft release for Signum Node

on:
  push:
    tags:
      - 'v*'

jobs:
  build-node:
    name: Build and Package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version from tag
        id: get_version
        shell: bash
        run: |
          echo VERSION=${{github.ref_name}}
          echo VERSION=${{github.ref_name}} >> $GITHUB_ENV

      - name: Show version
        shell: bash
        run: echo "Version is $VERSION"

      - name: Update Wallets
        shell: bash
        run: |
          cd ./ci
          ./updatePhoenix.sh
          ./updateClassic.sh

      - name: Set up Java 25 (Zulu)
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Build artifacts
        run: ./gradlew unzipWindowsJDK shadowJar jpackageWin jpackageWinSlim zipWinExe zipWinExeSlim release

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true

      - name: Upload - signum-node.zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./build/distributions/signum-node.zip
          file_rename: true
          file_name: signum-node-${{ env.VERSION }}.zip

      - name: Upload - signum-node-win_x64-with-browser.zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./build/distributions/signum-node-win_x64-with-browser.zip
          file_rename: true
          file_name: signum-node-${{ env.VERSION }}-win_x64-with-browser.zip

      - name: Upload - signum-node-win_x64-slim.zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ./build/distributions/signum-node-win_x64-slim.zip
          file_rename: true
          file_name: signum-node-${{ env.VERSION }}-win_x64-slim.zip
