name: Draft release for Signum Node

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-openapi:
    name: Build OpenAPI on Linux
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build OpenAPI
        run: ./gradlew buildOpenApi

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-html
          path: html/api-doc/

  build-node:
    name: Build and Package on Windows
    needs: build-openapi
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Wallets
        shell: bash
        run: |
          cd ./ci
          ./updatePhoenix.sh
          ./updateClassic.sh

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi-html
          path: html/api-doc/

      - name: Set up Java 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build artifacts
        run: ./gradlew unzipWindowsJDK shadowJar jpackageWin zipWinExe release

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release Draft
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Signum Node ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload - signum-node.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node.zip
          asset_name: signum-node-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload - signum-node-win_x64.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/signum-node-win_x64.zip
          asset_name: signum-node-${{ env.VERSION }}-win_x64.zip
          asset_content_type: application/zip
